type: object
description: |
  The Ocean cluster.
required:
  - name
  - controllerClusterId
properties:
  id:
    type: string
    readOnly: true
    example: o-134abcd
    description: |
      Ocean cluster ID.
  name:
    type: string
    example: test
    description: |
      Add a name for the Ocean cluster.
  controllerClusterId:
    type: string
    example: test-123124
    description: |
      Enter a unique Ocean cluster identifier. Cannot be updated.
  createdAt:
    type: string
    readOnly: true
    format: date-time
    example: "2021-03-17T08:13:08.000Z"
    description: |
      A timestamp of the Ocean creation
  updatedAt:
    type: string
    readOnly: true
    format: date-time
    example: "2021-03-17T15:06:13.000Z"
    description: |
      A timestamp of the latest Ocean update