type: object
description: The cloud cost of the Spark application. Updated every hour
required:
- total
- createdAt
- updatedAt
properties:
  createdAt:
    # I had to write createdAt and updatedAt manually and not use createdAtUpdatedAt.yaml.
    # Otherwise the object is marked as "recursive". This looks like a redoc bug.
    $ref: "createdAt.yaml"
  updatedAt:
    $ref: "updatedAt.yaml"
  total:
    type: integer
    description: The total cost of the Spark application in USD cents
    example: 0
