summary: Ocean CD
get:
  summary: "Get Ocean CD Environment"
  description: >
    Get an existing Ocean CD Environment.
  operationId: "oceanCDEnvironmentGet"
  tags:
    - "Ocean CD"
  parameters:
    - in: "path"
      name: "environmentName"
      schema:
        type: "string"
      required: true
      example: prod
      description: >
        The identifier name of the Ocean CD Environment
  responses:
    200:
      $ref: "../responses/oceanCDEnvResponse.yaml"
    400:
      description: "Bad Request"
put:
  summary: "Update Ocean CD Environment"
  description: >
    Full Update of Ocean CD environment configuration.

    *All non included fields will be nullified*
  operationId: "OceanCDEnvironmentUpdate"
  tags:
    - "Ocean CD"
  parameters:
    - in: "path"
      name: "environmentName"
      schema:
        type: "string"
      required: true
      example: prod
      description: >
        The identifier name of the Ocean CD Environment
  requestBody:
    required: true
    content:
      application/json:
        schema:
          allOf:
            - $ref: "../schemas/oceanCDEnvUpdateRequest.yaml"
  responses:
    200:
      description: "Ok"
    400:
      description: "Bad Request"
patch:
  summary: "Patch Ocean CD Environment"
  description: >
    Partial update Ocean CD environment configuration.
  operationId: "OceanCDEnvironmentPatch"
  tags:
    - "Ocean CD"
  parameters:
    - in: "path"
      name: "environmentName"
      schema:
        type: "string"
      required: true
      example: prod
      description: >
        The identifier name of the Ocean CD Environment
  requestBody:
    required: true
    content:
      application/json:
        schema:
          allOf:
            - $ref: "../schemas/oceanCDEnvPatchRequest.yaml"
  responses:
    200:
      description: "Ok"
    400:
      description: "Bad Request"
delete:
  summary: "Delete Ocean CD Environment"
  description: >
    Delete an existing Ocean CD environment.
  operationId: "OceanCDEnvironmentDelete"
  tags:
    - "Ocean CD"
  parameters:
    - in: "path"
      name: "environmentName"
      schema:
        type: "string"
      required: true
      example: prod
      description: >
        The identifier name of the Ocean CD Environment
  responses:
    200:
      description: "Ok"
    400:
      description: "Bad Request"
